providers/ab-cell-kyivstar/main.js

Минуты на другие мобильные: (со сроком действия) и Интернет:

Изменения Киевстар

---

providers/ab-internet-netberry/anybalance-manifest.xml
providers/ab-internet-netberry/history.xml
providers/ab-internet-netberry/main.js

Существенные изменения на сайте биллинга Netberry (Беларусь).
Модуль провайдера скорректирован.

Поддержка изменений на сайте биллинга провайдера Netberry (Беларусь)

---

providers/ab-internet-dialog/main.js

- Добавлены новые счетчики: Скорость подключения, Дата и время подключения, IP-адрес, Адрес подключения.
- Удалены устаревшие счетчики (турбо скорость).
- Оптимизация энергопотребления.

На сайте изменения, подправил код + новые счетчики

---

providers/ab-bonus-sparcard/anybalance-manifest.xml
providers/ab-bonus-sparcard/main.js

Provider's site has been changed. The plugin "ab-bonus-sparcard" is updated to v7.

ab-bonus-sparcard v7

---

providers/ab-internet-stupinoSU/anybalance-manifest.xml
providers/ab-internet-stupinoSU/history.xml
providers/ab-internet-stupinoSU/main.js
providers/ab-service-docsgroup/anybalance-manifest.xml
providers/ab-service-docsgroup/history.xml
providers/ab-service-docsgroup/main.js
providers/ab-service-docsgroup/preferences.xml

ab-internet-stupinosu Добавлен альтернативный сервер для стабильности

обновил ab-internet-stupinosu & ab-service-docsgroup

---

providers/ab-bonus-prostokvashino-rus/anybalance-manifest.xml
providers/ab-bonus-prostokvashino-rus/history.xml
providers/ab-bonus-prostokvashino-rus/main.js

Изменения провайдера "Простоквашино (Россия)"

Поддержка изменений на сайте. Добавлен новый счетчик - Баланс рублей

---

providers/ab-internet-disconttelecom/anybalance-manifest.xml
providers/ab-internet-disconttelecom/history.xml
providers/ab-internet-disconttelecom/main.js

Дисконт Телеком (ab-internet-disconttelecom):

---

providers/ab-cell-altel4g/anybalance-manifest.xml
providers/ab-cell-altel4g/history.xml
providers/ab-cell-altel4g/main.js

ALTEL 4G (Казахстан) (ab-cell-altel4g):

---

providers/ab-cell-telenor/anybalance-manifest.xml
providers/ab-cell-telenor/history.xml
providers/ab-cell-telenor/library.js
providers/ab-cell-telenor/main.js

http://support.anybalance.ru/scp/tickets.php?id=6009

Поддержка изменений на сайте (ab-cell-telenor)

---

providers/ab-money-forex4you/anybalance-manifest.xml
providers/ab-money-forex4you/history.xml
providers/ab-money-forex4you/main.js
providers/ab-money-forex4you/preferences.xml

http://support.anybalance.ru/scp/tickets.php?id=5582

Поддержка изменений на сайте (ab-money-forex4you)

---

providers/ab-bonus-ikra/anybalance-manifest.xml
providers/ab-bonus-ikra/history.xml
providers/ab-bonus-ikra/main.js

http://support.anybalance.ru/scp/tickets.php?id=5741

Поддержка изменений на сайте (ab-bonus-ikra)

---

providers/ab-affiliate-faberlic/anybalance-manifest.xml
providers/ab-affiliate-faberlic/history.xml
providers/ab-affiliate-faberlic/library.js
providers/ab-affiliate-faberlic/main.js

http://support.anybalance.ru/scp/tickets.php?id=5708
http://support.anybalance.ru/scp/tickets.php?id=5837

Мелкие улучшения (ab-affiliate-faberlic)

---

providers/ab-internet-k-telecom/anybalance-manifest.xml
providers/ab-internet-k-telecom/history.xml
providers/ab-internet-k-telecom/library.js
providers/ab-internet-k-telecom/main.js

http://support.anybalance.ru/scp/tickets.php?id=5647
http://support.anybalance.ru/scp/tickets.php?id=6006

Мелкие улучшения (ab-internet-k-telecom)

---

providers/ab-cell-orange-pl/anybalance-manifest.xml
providers/ab-cell-orange-pl/history.xml
providers/ab-cell-orange-pl/library.js
providers/ab-cell-orange-pl/main.js

http://support.anybalance.ru/scp/tickets.php?id=2943

Добавлены счётчики (ab-cell-orange-pl)

---

providers/ab-bonus-kopilka/anybalance-manifest.xml
providers/ab-bonus-kopilka/history.xml
providers/ab-bonus-kopilka/main.js
providers/ab-bonus-kopilka/preferences.xml

http://support.anybalance.ru/scp/tickets.php?id=5844

Поддержка изменений на сайте (ab-bonus-kopilka)

---

providers/ab-municipal-kievgaz/anybalance-manifest.xml
providers/ab-municipal-kievgaz/history.xml
providers/ab-municipal-kievgaz/main.js

http://support.anybalance.ru/scp/tickets.php?id=5733

Поддержка изменений на сайте (ab-municipal-kievgaz)

---

providers/ab-game-wot/anybalance-manifest.xml
providers/ab-game-wot/history.xml
providers/ab-game-wot/main.js

http://support.anybalance.ru/scp/tickets.php?id=4851
http://support.anybalance.ru/scp/tickets.php?id=4491
http://support.anybalance.ru/scp/tickets.php?id=4099
http://support.anybalance.ru/scp/tickets.php?id=6161

Мелкие улучшения (ab-game-wot)

---

providers/ab-internet-skyengineering/anybalance-manifest.xml
providers/ab-internet-skyengineering/history.xml
providers/ab-internet-skyengineering/main.js

http://support.anybalance.ru/scp/tickets.php?id=4323

Новый провайдер Sky Engineering

---

providers/ab-internet-intersvyaz/anybalance-manifest.xml
providers/ab-internet-intersvyaz/history.xml
providers/ab-internet-intersvyaz/library.js
providers/ab-internet-intersvyaz/main.js

Интерсвязь (Челябинск) (ab-internet-intersvyaz):

---

providers/ab-service-yandex-market/anybalance-manifest.xml
providers/ab-service-yandex-market/history.xml
providers/ab-service-yandex-market/library.js
providers/ab-service-yandex-market/main.js

Яндекс Маркет (ab-service-yandex-market):

---

providers/ab-social-odnoklassniki/anybalance-manifest.xml
providers/ab-social-odnoklassniki/history.xml
providers/ab-social-odnoklassniki/library.js
providers/ab-social-odnoklassniki/main.js

Исправлено получение имени пользователя

Одноклассники (ab-social-odnoklassniki):

---

providers/ab-cell-megafon-korp/anybalance-manifest.xml
providers/ab-cell-megafon-korp/history.xml
providers/ab-cell-megafon-korp/main.js

Мегафон корпоративный (ab-cell-megafon-korp):

---

extra/development/ab-nadapter-typical-provider/_history.bat
extra/development/ab-stark-typical-provider/_history.bat

rr update _history.bat

---

providers/ab-tv-i-ghost/anybalance-manifest.xml
providers/ab-tv-i-ghost/history.xml
providers/ab-tv-i-ghost/library.js
providers/ab-tv-i-ghost/main.js

http://support.anybalance.ru/scp/tickets.php?id=4684

rr update I-GHOST

---

providers/ab-municipal-yaltateplo-krim/anybalance-manifest.xml
providers/ab-municipal-yaltateplo-krim/history.xml
providers/ab-municipal-yaltateplo-krim/library.js
providers/ab-municipal-yaltateplo-krim/main.js

http://support.anybalance.ru/scp/tickets.php?id=4779

rr update Крымтеплокоммунэнерго Ялта

---

providers/ab-transport-m-road/anybalance-manifest.xml
providers/ab-transport-m-road/history.xml
providers/ab-transport-m-road/library.js
providers/ab-transport-m-road/main.js

http://support.anybalance.ru/scp/tickets.php?id=4609

rr update  ООО "Новое качество дорог"

---

providers/ab-municipal-bashesk/anybalance-manifest.xml
providers/ab-municipal-bashesk/history.xml
providers/ab-municipal-bashesk/library.js
providers/ab-municipal-bashesk/main.js

http://support.anybalance.ru/scp/tickets.php?id=4129
Ticket #324877
update and fixes (uncluduing rename)

rr update РУСГИДРО Башкортостан

---

providers/ab-tracking-belpost/anybalance-manifest.xml
providers/ab-tracking-belpost/history.xml
providers/ab-tracking-belpost/library.js
providers/ab-tracking-belpost/main.js
providers/ab-tracking-belpost/preferences.xml

http://support.anybalance.ru/scp/tickets.php?id=5561

rr update Белпост (ab-tracking-belpost)

---

providers/ab-internet-ttk/anybalance-manifest.xml
providers/ab-internet-ttk/history.xml
providers/ab-internet-ttk/main.js

ТТК (Единый кабинет) (ab-internet-ttk):

---

providers/ab-bonus-sportmaster/anybalance-manifest.xml
providers/ab-bonus-sportmaster/history.xml
providers/ab-bonus-sportmaster/main.js

Исправлена обработка ошибок авторизации (провайдер не обнаруживал факт неправильного логина/пароля и не прекращал работу)

Спортмастер (ab-bonus-sportmaster):

---

providers/ab-bonus-avtomir/anybalance-manifest.xml
providers/ab-bonus-avtomir/history.xml
providers/ab-bonus-avtomir/main.js

Автомир (Бонусы) (ab-bonus-avtomir):

---

providers/ab-bonus-ochkarik/anybalance-manifest.xml
providers/ab-bonus-ochkarik/history.xml
providers/ab-bonus-ochkarik/main.js

Очкарик (ab-bonus-ochkarik):

---

providers/ab-tracking-ems-ukraine/anybalance-manifest.xml

ems-ukraine provider

---

providers/ab-bonus-mts20/anybalance-manifest.xml
providers/ab-bonus-mts20/history.xml
providers/ab-bonus-mts20/main.js
providers/ab-bonus-mts20/preferences.xml

http://support.anybalance.ru/scp/tickets.php?id=6281

Поддержка изменений на сайте (ab-bonus-mts20)

---

providers/ab-fine-tatar/anybalance-manifest.xml
providers/ab-fine-tatar/history.xml
providers/ab-fine-tatar/main.js

http://support.anybalance.ru/scp/tickets.php?id=5517

Изменения в обработке штрафов (ab-fine-tatar)

---

providers/ab-fine-yandex/anybalance-manifest.xml
providers/ab-fine-yandex/history.xml
providers/ab-fine-yandex/main.js

http://support.anybalance.ru/scp/tickets.php?id=5459
http://support.anybalance.ru/scp/tickets.php?id=5411
http://support.anybalance.ru/scp/tickets.php?id=5349
http://support.anybalance.ru/scp/tickets.php?id=4713
http://support.anybalance.ru/scp/tickets.php?id=5048

Улучшена обработка ошибок (ab-fine-yandex)

---

providers/ab-municipal-enpf-kz/anybalance-manifest.xml

http://support.anybalance.ru/scp/tickets.php?id=4067
Поправил в манифесте ссылки и страну

Adjust manifest links and country

---

providers/ab-finance-toshl/anybalance-manifest.xml
providers/ab-finance-toshl/history.xml
providers/ab-finance-toshl/main.js
providers/ab-finance-toshl/preferences.xml

http://support.anybalance.ru/scp/tickets.php?id=5886

Фикс кук (ab-finance-toshl)

---

providers/ab-hosting-registrant/anybalance-manifest.xml
providers/ab-hosting-registrant/history.xml
providers/ab-hosting-registrant/main.js

Registrant (домены) (ab-hosting-registrant):

---

providers/ab-guard-uvokuzbass/anybalance-manifest.xml
providers/ab-guard-uvokuzbass/history.xml
providers/ab-guard-uvokuzbass/main.js

http://support.anybalance.ru/scp/tickets.php?id=6598

uvokuzbass provider

---

providers/ab-cell-orange-md/anybalance-manifest.xml
providers/ab-cell-orange-md/history.xml
providers/ab-cell-orange-md/main.js

http://support.anybalance.ru/scp/tickets.php?id=5398
http://support.anybalance.ru/scp/tickets.php?id=6243

Поддержка изменений на сайте (ab-cell-orange-md)

---

providers/ab-internet-putilovka/anybalance-manifest.xml
providers/ab-internet-putilovka/history.xml
providers/ab-internet-putilovka/main.js

http://support.anybalance.ru/scp/tickets.php?id=6728

Putilovka provider

---

providers/ab-internet-inetvdom/anybalance-manifest.xml
providers/ab-internet-inetvdom/history.xml
providers/ab-internet-inetvdom/main.js

http://support.anybalance.ru/scp/tickets.php?id=4836

inetvdom provider

---

providers/ab-municipal-gazprom/anybalance-manifest.xml
providers/ab-municipal-gazprom/history.xml
providers/ab-municipal-gazprom/main.js
providers/ab-municipal-gazprom/preferences.xml

http://support.anybalance.ru/scp/tickets.php?id=6701

Новый регион: Воронеж (ab-municipal-gazprom)

---

providers/ab-internet-avk-wellcom/anybalance-manifest.xml
providers/ab-internet-avk-wellcom/history.xml
providers/ab-internet-avk-wellcom/main.js

Изменился урл, так же провайдер теперь работает только в локальной сети

АВК-ВЕЛЛКОМ (ab-internet-avk-wellcom):

---

providers/ab-internet-infolink/anybalance-manifest.xml
providers/ab-internet-infolink/history.xml
providers/ab-internet-infolink/main.js

поддержка отрицательного баланса

Инфолинк (ab-internet-infolink):

---

providers/ab-internet-kievstar/anybalance-manifest.xml
providers/ab-internet-kievstar/history.xml
providers/ab-internet-kievstar/main.js

http://support.anybalance.ru/scp/tickets.php?id=6398

rr update Киевстар Интернет (ab-internet-kievstar)

---

providers/ab-cell-kyivstar/anybalance-manifest.xml
providers/ab-cell-kyivstar/history.xml
providers/ab-cell-kyivstar/main.js

http://support.anybalance.ru/scp/tickets.php?id=6402
http://support.anybalance.ru/scp/tickets.php?id=6501
http://support.anybalance.ru/scp/tickets.php?id=6611

rr update Киевстар (ab-cell-kyivstar)

---

providers/ab-exchange-alfabank/anybalance-manifest.xml

rr small update  (ab-exchange-alfabank)

---

providers/ab-internet-sirenko-isp/anybalance-manifest.xml
providers/ab-internet-sirenko-isp/history.xml

Sirenko ISP (ab-internet-sirenko-isp):

---

providers/ab-bonus-kopilka/anybalance-manifest.xml
providers/ab-bonus-kopilka/history.xml
providers/ab-bonus-kopilka/main.js

http://support.anybalance.ru/scp/tickets.php?id=6278

bonus-kopilka provider

---

providers/ab-cell-kcell-kz/anybalance-manifest.xml
providers/ab-cell-kcell-kz/history.xml
providers/ab-cell-kcell-kz/main.js

http://support.anybalance.ru/scp/tickets.php?id=6801

kcell-kz provider

---

providers/ab-municipal-rkcgku-surgut/anybalance-manifest.xml
providers/ab-municipal-rkcgku-surgut/history.xml

исправления в манифесте
http://support.anybalance.ru/scp/tickets.php?id=6720

РКЦ ЖКУ г. Сургута (ab-municipal-rkcgku-surgut):

---

providers/ab-money-energynpf/anybalance-manifest.xml
providers/ab-money-energynpf/history.xml
providers/ab-money-energynpf/main.js

http://support.anybalance.ru/scp/tickets.php?id=6324

Energy Npfe

---

providers/ab-telephony-callbacker/anybalance-manifest.xml
providers/ab-telephony-callbacker/history.xml
providers/ab-telephony-callbacker/main.js

http://support.anybalance.ru/scp/tickets.php?id=6488

Callbacker

---

providers/ab-service-m11/anybalance-manifest.xml

http://support.anybalance.ru/scp/tickets.php?id=6911

m11 - provider, add RUB suffix

---

providers/ab-exchange-rosbank/anybalance-manifest.xml
providers/ab-exchange-rosbank/history.xml
providers/ab-exchange-rosbank/main.js

http://support.anybalance.ru/scp/tickets.php?id=5821

rosbank provider

---

providers/ab-bonus-bashneft/anybalance-manifest.xml
providers/ab-bonus-bashneft/history.xml
providers/ab-bonus-bashneft/main.js

http://support.anybalance.ru/scp/tickets.php?id=6807

bashneft provider

---

providers/ab-seo-tnx/anybalance-manifest.xml
providers/ab-seo-tnx/history.xml
providers/ab-seo-tnx/main.js

http://support.anybalance.ru/scp/tickets.php?id=6806

seo-tnx provider

---

providers/ab-internet-iformula/anybalance-manifest.xml
providers/ab-internet-iformula/history.xml
providers/ab-internet-iformula/main.js

http://support.anybalance.ru/scp/tickets.php?id=6387

iformula provider

---

providers/ab-internet-protvino/anybalance-manifest.xml
providers/ab-internet-protvino/history.xml
providers/ab-internet-protvino/main.js

http://support.anybalance.ru/scp/tickets.php?id=6681

Protvino provider

---

providers/ab-municipal-tek-energo/anybalance-manifest.xml

Изменено название и описание провайдера (по требованию клиента)

ТЭК-Энерго (ab-municipal-tek-energo)

---

providers/ab-service-altfater/anybalance-manifest.xml
providers/ab-service-altfater/history.xml
providers/ab-service-altfater/main.js
providers/ab-service-altfater/preferences.xml

http://support.anybalance.ru/scp/tickets.php?id=6512

Altfater Crimea provider

---

providers/ab-internet-indicom/anybalance-manifest.xml
providers/ab-internet-indicom/history.xml
providers/ab-internet-indicom/main.js

Ticket #887024
Поддержка перехода сайта на https протокол.

Индиком (Мытищи) (ab-internet-indicom)

---

providers/ab-bonus-xtk19/anybalance-manifest.xml
providers/ab-bonus-xtk19/history.xml
providers/ab-bonus-xtk19/main.js
providers/ab-bonus-xtk19/preferences.xml

http://support.anybalance.ru/scp/tickets.php?id=6932

bonus-xtk19 provider

---

providers/ab-bonus-xtk19/main.js

http://support.anybalance.ru/scp/tickets.php?id=6932

xtk19 provider

---

providers/ab-internet-disconttelecom/anybalance-manifest.xml
providers/ab-internet-disconttelecom/history.xml
providers/ab-internet-disconttelecom/main.js

http://support.anybalance.ru/scp/tickets.php?id=6986

disconttelecom provider

---

providers/ab-municipal-pitersbyt/anybalance-manifest.xml
providers/ab-municipal-pitersbyt/history.xml
providers/ab-municipal-pitersbyt/main.js

http://support.anybalance.ru/scp/tickets.php?id=7008

pitersbyt provider

---

providers/ab-internet-nvrnet/anybalance-manifest.xml
providers/ab-internet-nvrnet/history.xml
providers/ab-internet-nvrnet/main.js

Спринт (ab-internet-nvrnet)

---

providers/ab-tv-telekarta/anybalance-manifest.xml
providers/ab-tv-telekarta/history.xml
providers/ab-tv-telekarta/main.js

http://support.anybalance.ru/scp/tickets.php?id=6930

telekarta provider

---

providers/ab-municipal-energosbyt/anybalance-manifest.xml
providers/ab-municipal-energosbyt/history.xml

Исправлена ссылка на личный кабинет
http://support.anybalance.ru/scp/tickets.php?id=3744

Энергосбыт

---

providers/ab-money-lukoil-npf/anybalance-manifest.xml
providers/ab-money-lukoil-npf/history.xml
providers/ab-money-lukoil-npf/main.js

http://support.anybalance.ru/scp/tickets.php?id=6857
http://support.anybalance.ru/scp/tickets.php?id=6865
http://support.anybalance.ru/scp/tickets.php?id=6234

Лукойл НПФ (ab-money-lukoil-npf)

---

providers/ab-municipal-system-gorod/anybalance-manifest.xml
providers/ab-municipal-system-gorod/history.xml
providers/ab-municipal-system-gorod/main.js

http://support.anybalance.ru/scp/tickets.php?id=6775
http://support.anybalance.ru/scp/tickets.php?id=5935
http://support.anybalance.ru/scp/tickets.php?id=5836

Система Город (ab-municipal-system-gorod)

---

providers/ab-exchange-btc-e/anybalance-manifest.xml
providers/ab-exchange-btc-e/history.xml
providers/ab-exchange-btc-e/main.js

http://support.anybalance.ru/scp/tickets.php?id=6895

btc-e provider

---

providers/ab-municipal-krimenergo/anybalance-manifest.xml
providers/ab-municipal-krimenergo/history.xml
providers/ab-municipal-krimenergo/main.js

http://support.anybalance.ru/scp/tickets.php?id=6778

krimenergo provider

---

providers/ab-internet-dialog/anybalance-manifest.xml
providers/ab-internet-dialog/history.xml
providers/ab-internet-dialog/main.js

http://support.anybalance.ru/scp/tickets.php?id=7048

rr fix Диалог г. Калининград (ab-internet-dialog)

---

providers/ab-municipal-erc-ur/anybalance-manifest.xml
providers/ab-municipal-erc-ur/history.xml
providers/ab-municipal-erc-ur/library.js
providers/ab-municipal-erc-ur/main.js
providers/ab-municipal-erc-ur/preferences.xml

http://support.anybalance.ru/scp/tickets.php?id=5768

rr update ЕРЦ Екатеринбург (ab-municipal-erc-ur)

---

providers/ab-cell-kyivstar/anybalance-manifest.xml
providers/ab-cell-kyivstar/history.xml
providers/ab-cell-kyivstar/main.js

http://support.anybalance.ru/scp/tickets.php?id=7068
http://support.anybalance.ru/scp/tickets.php?id=6956

rr update Киевстар

---

providers/ab-tv-tricolor/anybalance-manifest.xml
providers/ab-tv-tricolor/history.xml
providers/ab-tv-tricolor/main.js

http://support.anybalance.ru/scp/tickets.php?id=6952

tricolor provider

---

providers/ab-fine-tatar/anybalance-manifest.xml
providers/ab-fine-tatar/history.xml
providers/ab-fine-tatar/main.js

http://support.anybalance.ru/scp/tickets.php?id=5222

fine-tatar provider

---

providers/ab-cell-teletai/anybalance-manifest.xml
providers/ab-cell-teletai/history.xml
providers/ab-cell-teletai/main.js

http://support.anybalance.ru/scp/tickets.php?id=7141
http://support.anybalance.ru/scp/tickets.php?id=7139

протокол изменен на https

---

providers/ab-bonus-euroopt/anybalance-manifest.xml
providers/ab-bonus-euroopt/history.xml
providers/ab-bonus-euroopt/main.js

http://support.anybalance.ru/scp/tickets.php?id=7111

исправления main.js

---

providers/ab-municipal-rkcgku-surgut/anybalance-manifest.xml
providers/ab-municipal-rkcgku-surgut/history.xml
providers/ab-municipal-rkcgku-surgut/main.js

- трим для всех введенных значений
http://support.anybalance.ru/scp/tickets.php?id=6720

ab-municipal-rkcgku-surgut

---

providers/ab-tracking-moyaposylka/anybalance-manifest.xml
providers/ab-tracking-moyaposylka/history.xml
providers/ab-tracking-moyaposylka/main.js

Дружественное сообщение об ошибке

Моя посылка (ab-tracking-moyaposylka)

---

providers/ab-service-smsc/anybalance-manifest.xml
providers/ab-service-smsc/history.xml
providers/ab-service-smsc/main.js

http://support.anybalance.ru/scp/tickets.php?id=7043

service-smsc provider

---

providers/ab-internet-tiera/anybalance-manifest.xml
providers/ab-internet-tiera/history.xml
providers/ab-internet-tiera/main.js

http://support.anybalance.ru/scp/tickets.php?id=7080

поддержка изменений на сайте Ticket #793906

---

providers/ab-bonus-mts20/anybalance-manifest.xml
providers/ab-bonus-mts20/history.xml
providers/ab-bonus-mts20/main.js

http://support.anybalance.ru/scp/tickets.php?id=7065
http://support.anybalance.ru/scp/tickets.php?id=6281

Исправлена ошибка получения информации о балансе (ab-bonus-mts20)

---

providers/ab-internet-beeline/anybalance-manifest.xml
providers/ab-internet-beeline/history.xml
providers/ab-internet-beeline/main.js
providers/ab-internet-beeline/preferences.xml

http://support.anybalance.ru/scp/tickets.php?id=7078

добавлен кабинет Ticket #762927

---

providers/ab-cell-teletai/anybalance-manifest.xml
providers/ab-cell-teletai/history.xml
providers/ab-cell-teletai/main.js

http://support.anybalance.ru/scp/tickets.php?id=7109

ab-cell-teletai Ticket #172647

---

providers/ab-exchange-aliexpress/anybalance-manifest.xml
providers/ab-exchange-aliexpress/history.xml
providers/ab-exchange-aliexpress/main.js

Добавлен polyfill для метода Array.prototype.find
Ticket #232592

Курс доллара AliExpress (ab-exchange-aliexpress)

---

providers/ab-hosting-hostland/anybalance-manifest.xml
providers/ab-hosting-hostland/main.js

в новом провайдере заметил ошибку
тикета нет, номер версии не менял

исправил ошибку в ab-hosting-hostland

---

providers/ab-cell-whyfly/anybalance-manifest.xml
providers/ab-cell-whyfly/history.xml
providers/ab-cell-whyfly/main.js

улучшена выдача счетчиков

---

providers/ab-municipal-gazprom/anybalance-manifest.xml
providers/ab-municipal-gazprom/history.xml
providers/ab-municipal-gazprom/main.js

http://support.anybalance.ru/scp/tickets.php?id=7238

Тверь: поддержка изменений на сайте. (ab-municipal-gazprom)

---

providers/ab-bonus-lufthansa/anybalance-manifest.xml
providers/ab-bonus-lufthansa/history.xml
providers/ab-bonus-lufthansa/main.js

http://support.anybalance.ru/scp/tickets.php?id=7109

поддержка изменений ab-bonus-lufthansa

---

providers/ab-telephony-zadarma/anybalance-manifest.xml
providers/ab-telephony-zadarma/history.xml
providers/ab-telephony-zadarma/main.js

http://support.anybalance.ru/scp/tickets.php?id=7161

zadarma provider

---

providers/ab-service-altfater/anybalance-manifest.xml
providers/ab-service-altfater/history.xml
providers/ab-service-altfater/main.js

http://support.anybalance.ru/scp/tickets.php?id=7222

ab-service-altfater provider

---

providers/ab-internet-2kom/anybalance-manifest.xml
providers/ab-internet-2kom/history.xml
providers/ab-internet-2kom/main.js

http://support.anybalance.ru/scp/tickets.php?id=7266

Добавлены новые счётчики (ab-internet-2kom)

---

providers/ab-bonus-gazprom/anybalance-manifest.xml
providers/ab-bonus-gazprom/history.xml
providers/ab-bonus-gazprom/main.js

1) http://support.anybalance.ru/scp/tickets.php?id=7480
2) http://support.anybalance.ru/scp/tickets.php?id=7443
3) http://support.anybalance.ru/scp/tickets.php?id=7378
4) http://support.anybalance.ru/scp/tickets.php?id=7220  - тут какая-то другая ошибка. Я не знаю, что это.
Upd.  к тикету №4: оказывается, подобные заявки от этого пользователя уже поступали:
- http://support.anybalance.ru/scp/tickets.php?id=6647
- http://support.anybalance.ru/scp/tickets.php?id=6928

Исправлена ошибка (ab-bonus-gazprom)

---

providers/ab-municipal-104ua/main.js

http://support.anybalance.ru/scp/tickets.php?id=7093

ab-municipal-104ua provider

---

providers/ab-money-russipoteka/anybalance-manifest.xml
providers/ab-money-russipoteka/history.xml

1) http://support.anybalance.ru/scp/tickets.php?id=7495

Исправлена ошибка со счётчиком (ab-money-russipoteka)

---

providers/ab-municipal-gazprom/anybalance-manifest.xml
providers/ab-municipal-gazprom/history.xml
providers/ab-municipal-gazprom/main.js
providers/ab-municipal-gazprom/preferences.xml

1) http://support.anybalance.ru/scp/tickets.php?id=7642

Добавлен новый регион: Север.

---

providers/ab-internet-netbynet/anybalance-manifest.xml
providers/ab-internet-netbynet/history.xml
providers/ab-internet-netbynet/main.js

1) http://support.anybalance.ru/scp/tickets.php?id=7638

Исправлен регион "Екатеринбург" (ab-internet-netbynet)

---

providers/ab-municipal-ekenergosbyt/anybalance-manifest.xml
providers/ab-municipal-ekenergosbyt/history.xml
providers/ab-municipal-ekenergosbyt/main.js

1) http://support.anybalance.ru/scp/tickets.php?id=7562

Исправлен счётчик "Баланс" (ab-municipal-ekenergosbyt)

---

providers/ab-municipal-ekgaz/anybalance-manifest.xml
providers/ab-municipal-ekgaz/history.xml
providers/ab-municipal-ekgaz/main.js

1) http://support.anybalance.ru/scp/tickets.php?id=7563

Добавлен новый счётчик (ab-municipal-ekgaz)

---

providers/ab-municipal-svenergo/main.js

http://support.anybalance.ru/scp/tickets.php?id=7525

ab-municipal-svenergo provider -> adjust balance counter

---

providers/ab-municipal-ekenergosbyt/main.js
providers/ab-municipal-ekgaz/main.js

1) http://support.anybalance.ru/scp/tickets.php?id=7563

Мелкие изменения (ab-municipal-ekgaz & ab-municipal-ekenergosbyt).

---

providers/ab-telephony-plusofon/anybalance-manifest.xml
providers/ab-telephony-plusofon/history.xml
providers/ab-telephony-plusofon/main.js

1) http://support.anybalance.ru/scp/tickets.php?id=7526

Исправлено получение счётчиков (ab-telephony-plusofon)

---

providers/ab-bonus-belarus-neft/anybalance-manifest.xml
providers/ab-bonus-belarus-neft/history.xml
providers/ab-bonus-belarus-neft/main.js

1) http://support.anybalance.ru/scp/tickets.php?id=7573
upd. 28.04:
http://support.anybalance.ru/scp/tickets.php?id=7210

Добавлены счётчики (ab-bonus-belarus-neft)

---

providers/ab-municipal-activecitizen/anybalance-manifest.xml
providers/ab-municipal-activecitizen/history.xml
providers/ab-municipal-activecitizen/main.js

1) http://support.anybalance.ru/scp/tickets.php?id=7880
2) http://support.anybalance.ru/scp/tickets.php?id=7946
3) http://support.anybalance.ru/scp/tickets.php?id=7948

Поддержка изменений на сайте (ab-municipal-activecitizen)

---

providers/ab-money-priorbank/anybalance-manifest.xml
providers/ab-money-priorbank/history.xml
providers/ab-money-priorbank/main.js

There where some changes on site. After that provider stoped recognizing cards.
This regexp update fix this issue.

Update regexp for fetching cards (ab-money-priorbank)

---

providers/ab-bonus-sparcard/anybalance-manifest.xml
providers/ab-bonus-sparcard/main.js

ab-bonus-sparcard_12

---

providers/ab-hosting-beget/anybalance-manifest.xml
providers/ab-hosting-beget/history.xml
providers/ab-hosting-beget/main.js

1) http://support.anybalance.ru/scp/tickets.php?id=8841
2) http://support.anybalance.ru/scp/tickets.php?id=8850
3) http://support.anybalance.ru/scp/tickets.php?id=9043

Поддержка изменений на сайте (ab-hosting-beget)

---

providers/ab-municipal-itgkh/anybalance-manifest.xml
providers/ab-municipal-itgkh/history.xml
providers/ab-municipal-itgkh/main.js

1) http://support.anybalance.ru/scp/tickets.php?id=9296

Исправлены счётчики (ab-municipal-itgkh)

---

providers/ab-telephony-mixnet/anybalance-manifest.xml
providers/ab-telephony-mixnet/history.xml
providers/ab-telephony-mixnet/main.js

1) http://support.anybalance.ru/scp/tickets.php?id=9368

Поддержка изменений на сайте (ab-telephony-mixnet)

---

providers/ab-exchange-bloomberg/anybalance-manifest.xml
providers/ab-exchange-bloomberg/history.xml
providers/ab-exchange-bloomberg/main.js
providers/ab-exchange-bloomberg/preferences.xml

1) http://support.anybalance.ru/scp/tickets.php?id=8688
2) http://support.anybalance.ru/scp/tickets.php?id=9394
3) http://support.anybalance.ru/scp/tickets.php?id=9398

Поддержка изменений на сайте (ab-exchange-bloomberg)

---

providers/ab-money-elecsnet/main.js
providers/ab-municipal-104ua/anybalance-manifest.xml
providers/ab-municipal-104ua/history.xml
providers/ab-municipal-104ua/main.js

1) http://support.anybalance.ru/scp/tickets.php?id=9842

Поддержка изменений на сайте (ab-municipal-104ua)

---

providers/ab-sharing-cbilling/anybalance-manifest.xml
providers/ab-sharing-cbilling/history.xml
providers/ab-sharing-cbilling/main.js

1) http://support.anybalance.ru/scp/tickets.php?id=9924

Исправлено получение счётчика (ab-sharing-cbilling)

---

providers/ab-municipal-gazprom/anybalance-manifest.xml
providers/ab-municipal-gazprom/history.xml
providers/ab-municipal-gazprom/main.js
providers/ab-municipal-gazprom/preferences.xml

1) http://support.anybalance.ru/scp/tickets.php?id=9846

Добавлен новый регион: Рязань (ab-municipal-gazprom)

---

providers/ab-bonus-sportmaster/anybalance-manifest.xml
providers/ab-bonus-sportmaster/history.xml
providers/ab-bonus-sportmaster/main.js

1) http://support.anybalance.ru/scp/tickets.php?id=9919

Добавлен новый счётчик, поддержка изменений на сайте (ab-bonus-sportmaster)

---

providers/ab-transport-jojo/anybalance-manifest.xml
providers/ab-transport-jojo/history.xml
providers/ab-transport-jojo/main.js

Current version of ab-transport-jojo does not work, so this will fix it.
Also couple of additional fixed and improvements.

ab-transport-jojo urgent fixes and improvements

---

providers/ab-telephony-sipnet/anybalance-manifest.xml
providers/ab-telephony-sipnet/history.xml
providers/ab-telephony-sipnet/main.js

Исправлено получение ФИО
Новый счётчик Псевдоним

Поддержка изменений на сайте для SIPNET

---

providers/ab-education-glolime/main.js

Поддержка изменений на сайте https://school.glolime.ru/

Изменения провайдера ab-education-glolime

---

providers/ab-tv-netbynet/anybalance-manifest.xml
providers/ab-tv-netbynet/history.xml
providers/ab-tv-netbynet/main.js

1. http://support.anybalance.ru/scp/tickets.php?id=16220

Поддержка изменений на сайте (ab-tv-netbynet)

---

providers/ab-municipal-104ua/anybalance-manifest.xml
providers/ab-municipal-104ua/history.xml
providers/ab-municipal-104ua/main.js

1. http://support.anybalance.ru/scp/tickets.php?id=16216
2. http://support.anybalance.ru/scp/tickets.php?id=16129

Исправлено получение счётчика "баланс" (ab-municipal-104ua)

---

providers/ab-cell-pildyk/anybalance-manifest.xml
providers/ab-cell-pildyk/history.xml
providers/ab-cell-pildyk/main.js

1) http://support.anybalance.ru/scp/tickets.php?id=16202
http://support.anybalance.ru/scp/tickets.php?id=16148
2) http://support.anybalance.ru/scp/tickets.php?id=16204
http://support.anybalance.ru/scp/tickets.php?id=16183

Поддержка изменений на сайте (ab-cell-pildyk)

---

providers/ab-municipal-minsk-gov/anybalance-manifest.xml
providers/ab-municipal-minsk-gov/history.xml
providers/ab-municipal-minsk-gov/main.js

1. http://support.anybalance.ru/scp/tickets.php?id=15880
2. http://support.anybalance.ru/scp/tickets.php?id=15759
http://support.anybalance.ru/scp/tickets.php?id=15661
http://support.anybalance.ru/scp/tickets.php?id=15494

Поддержка изменений на сайте (ab-municipal-minsk-gov)

---

providers/ab-bonus-avantageclub/anybalance-manifest.xml
providers/ab-bonus-avantageclub/history.xml
providers/ab-bonus-avantageclub/main.js

1. http://support.anybalance.ru/scp/tickets.php?id=16087
http://support.anybalance.ru/scp/tickets.php?id=15789
2. http://support.anybalance.ru/scp/tickets.php?id=15685
3. http://support.anybalance.ru/scp/tickets.php?id=15504

Поддержка изменений на сайте (ab-bonus-avantageclub)

---

providers/ab-weather-foreca/anybalance-manifest.xml
providers/ab-weather-foreca/history.xml
providers/ab-weather-foreca/main.js

1. http://support.anybalance.ru/scp/tickets.php?id=15543

Поддержка изменений на сайте (ab-weather-foreca)

---

providers/ab-taxi-taxsee-driver/anybalance-manifest.xml
providers/ab-taxi-taxsee-driver/history.xml
providers/ab-taxi-taxsee-driver/main.js

1. http://support.anybalance.ru/scp/tickets.php?id=15569
http://support.anybalance.ru/scp/tickets.php?id=15798

Поддержка изменений на сайте (ab-taxi-taxsee)

---

providers/ab-bonus-kinomax/anybalance-manifest.xml
providers/ab-bonus-kinomax/history.xml
providers/ab-bonus-kinomax/main.js

1. http://support.anybalance.ru/scp/tickets.php?id=15823
2. http://support.anybalance.ru/scp/tickets.php?id=15580
http://support.anybalance.ru/scp/tickets.php?id=15606

Поддержка изменений на сайте (ab-bonus-kinomax)

---

providers/ab-bonus-21century/anybalance-manifest.xml
providers/ab-bonus-21century/history.xml
providers/ab-bonus-21century/main.js

1. http://support.anybalance.ru/scp/tickets.php?id=16273

Поддержка изменений на сайте (ab-bonus-21century)

---

providers/ab-bonus-vtb24/anybalance-manifest.xml
providers/ab-bonus-vtb24/history.xml
providers/ab-bonus-vtb24/main.js

1. http://support.anybalance.ru/scp/tickets.php?id=16330
2. http://support.anybalance.ru/scp/tickets.php?id=16378
3. http://support.anybalance.ru/scp/tickets.php?id=16257 (8 дубликатов)
4. http://support.anybalance.ru/scp/tickets.php?id=16332 (7 дубликатов)
5. http://support.anybalance.ru/scp/tickets.php?id=16103 (3 дубликата)
6. http://support.anybalance.ru/scp/tickets.php?id=16333
7. http://support.anybalance.ru/scp/tickets.php?id=16384
8. http://support.anybalance.ru/scp/tickets.php?id=16340
9. http://support.anybalance.ru/scp/tickets.php?id=16360
10. http://support.anybalance.ru/scp/tickets.php?id=16374
11. http://support.anybalance.ru/scp/tickets.php?id=16384

Поддержка изменений на сайте (ab-bonus-vtb24)

---

modules/extract/abe-money-rosbank/source/extract.js
providers/ab-money-rosbank/anybalance-manifest.xml
providers/ab-money-rosbank/history.xml
providers/ab-money-rosbank/main.js
providers/ab-money-rosbank/preferences.xml

Временно удалена поддержка депозитов.
Нужно сделать build.

Поддержка изменений на сайте (ab-money-rosbank)

---

providers/ab-bonus-ozon/anybalance-manifest.xml
providers/ab-bonus-ozon/history.xml
providers/ab-bonus-ozon/main.js

1. http://support.anybalance.ru/scp/tickets.php?id=16398
2. http://support.anybalance.ru/scp/tickets.php?id=15832
http://support.anybalance.ru/scp/tickets.php?id=15864
http://support.anybalance.ru/scp/tickets.php?id=16119
3. http://support.anybalance.ru/scp/tickets.php?id=16045

Поддержка изменений на сайте (ab-bonus-ozon)

---

providers/ab-money-gazfondpf/anybalance-manifest.xml
providers/ab-money-gazfondpf/history.xml
providers/ab-money-gazfondpf/main.js

1. http://support.anybalance.ru/scp/tickets.php?id=16472

Поддержка изменений на сайте (ab-money-gazfondpf)

---

providers/ab-municipal-tns-energo-nn/anybalance-manifest.xml
providers/ab-municipal-tns-energo-nn/history.xml
providers/ab-municipal-tns-energo-nn/main.js

ТНС энерго НН (ab-municipal-tns-energo-nn):

---

providers/ab-cell-life-by/anybalance-manifest.xml
providers/ab-cell-life-by/history.xml
providers/ab-cell-life-by/main.js

Исправление отображения и парсинга минут звонков в другие сети оператора Life:) BY

ab-cell-life-by

---

providers/ab-internet-taiget/anybalance-manifest.xml
providers/ab-internet-taiget/history.xml
providers/ab-internet-taiget/main.js

Увидел изменения у провайдера galaxy-net, но у меня без библиотеки не заработал Taiget. Поэтом я продолжаю использовать библиотеку файлом.

Поддержка изменений на сайте

---

providers/ab-cell-pildyk/anybalance-manifest.xml
providers/ab-cell-pildyk/history.xml
providers/ab-cell-pildyk/main.js

Сейчас у Pildyk не учитываются дополнительные тарифные опции (вроде «2 Гигабайта на месяц», «500 минут на месяц»). Добавил их поддержку в текущем виде, приложил пример возвращаемого респонса. Будут другие респонсы — увижу и поправлю их соответственно.

Поддержка дополнительного трафика и времени (ab-cell-pildyk).

---

providers/ab-internet-domtelecom/anybalance-manifest.xml
providers/ab-internet-domtelecom/history.xml
providers/ab-internet-domtelecom/main.js

Site location changed to my.datagroup.ua

Site location changed

---

providers/ab-municipal-itgkh/anybalance-manifest.xml
providers/ab-municipal-itgkh/history.xml
providers/ab-municipal-itgkh/main.js

ab-municipal-itgkh: согласие на обработку персональных данных

---

providers/ab-cell-megafon-korp/anybalance-manifest.xml
providers/ab-cell-megafon-korp/history.xml
providers/ab-cell-megafon-korp/main.js

Исправление для нескольких ЛС в одном ЛК

Версия 29: Исправление для нескольких ЛС в одном ЛК

---

providers/ab-internet-ecotelecom/main.js

После изменений в личном кабинете на сайте Экотелеком, перестал отображаться текущий баланс в Anybalnce. Исправил, теперь всё работает корректно.

Обновил main.js провайдера Экотелеком

---

providers/ab-municipal-erc-megabank/anybalance-manifest.xml
providers/ab-municipal-erc-megabank/history.xml
providers/ab-municipal-erc-megabank/main.js

+Добавлено распределение природного газа (новая услуга)
-Убран счетчик ФИО, т.к. сайт их больше не отображает

ab-municipal-erc-megabank  Добавлено распределение природного газа

---

modules/login/kyivstar/source/kyivstar_login.js
providers/ab-cell-kyivstar/anybalance-manifest.xml
providers/ab-cell-kyivstar/history.xml
providers/ab-money-privatbank-bisness/anybalance-manifest.xml
providers/ab-money-privatbank-bisness/history.xml
providers/ab-money-privatbank-bisness/main.js

ab-cell-kyivstar: изменен только magic_id в  modules/login/kyivstar/source/kyivstar_login.js и версия провайдера
ab-money-privatbank-bisness: переход на новый API банка.

ab-cell-kyivstar, ab-money-privatbank-bisness

---

providers/ab-cell-kyivstar/anybalance-manifest.xml

В манифест добавлен счётчик минут ну другие номера.
Таким образом данные значения будут доступны в приложении.

Провайдер ab-cell-kyivstar - Минуты на другие номера #1146

---

providers/ab-internet-planeta/main.js

Change baseurl address for Planeta

---

providers/ab-cell-megafon-korp/anybalance-manifest.xml
providers/ab-cell-megafon-korp/history.xml
providers/ab-cell-megafon-korp/main.js

Восстановлены переменные после переименования

ab-cell-megafon-korp Мегафон-Корп v34

---

providers/ab-money-privatbank/anybalance-manifest.xml
providers/ab-money-privatbank/api_new.js
providers/ab-money-privatbank/history.xml

Протестировано. Работает.
@DimaZUA JFYI

[ab-money-privatbank] Поддержка новой версии мобильного приложения
